Friendship feature
balerum03/ror-social-scaffold pull request #3
Opened 2020-11-04 21:29 UTC by balerum03

We created the table Friendship and at the same time generated the model with the logic so that those two tables are associated.

2020-11-04 22:51 UTC, blackpintz requested changes
# Status: Changes Required

### Hello team,

**Great job on your project. However, there are a few fixes needed.**

1). **There are no buttons/links that enable me to send friendship invitations to other users. The buttons should display on users list page and on the single-user page.**

users list page | user's page
---------------- | -----------
![userslistpage](https://user-images.githubusercontent.com/38922385/98172902-3933ef80-1f03-11eb-8ed1-b8e7cc7c8532.png) | ![users_page](https://user-images.githubusercontent.com/38922385/98172924-43ee8480-1f03-11eb-9901-11b89d3b6117.png)

2). **Ensure that the user who receives a friendship request gets to see it.**

3). **Create an accept and ignore button for the user who receives a friendship request. They need to click accept for the friendship to start. The ignore button rejects friendship.**

4). **The user's posts should only be seen by the user and the user's confirmed friends.**

5). **Add unit tests for the following files in the models folder - `comment.rb`, `post.rb`, `user.rb`, `like.rb`.**

6). **Write unit tests for your views and controllers folder. In the controller's folder, the focus should be on testing the routes. Hint: Check out this [link](https://open.appacademy.io/learn/full-stack-online/software-engineering-foundations/intro-to-testing-notes) on more about RSpec testing.**

7). **Check more in the comments below.**

## Happy coding 😃.

**PS: You can reach me on slack (Rose Wanjohi).**

2020-11-04 22:51 UTC, blackpintz commented on spec/requests/friendships_request_spec.rb
> +end
Remove this file since there are no written tests on it.

2020-11-04 22:51 UTC, blackpintz commented on spec/helpers/friendships_helper_spec.rb
> +end
Remove this file since it doesn't have written tests on it..

2020-11-08 04:10 UTC, voscarmv requested changes
# Nice work so far, team. 👍 

- Good work applying some of the previously requested changes.

## However, there are some changes required 👀 🧰 🔨 🔧 

- Please take some time to add views and controllers tests to your spec files, as requested by the previous TSE.
- Also, when I send a friendship request to another user, the other user can't accept the friend request. On their side, the page only shows:

![image](https://user-images.githubusercontent.com/2739245/98456662-062d6e00-2146-11eb-8350-f800496fa474.png)

There is no "accept friendship" button for the other user to accept my invitation. Please make sure that the other user can accept the invitation.

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-11-09 19:24 UTC, bmuhamood commented
Dear TSE, 
Greetings and Hope you fine and thanks a lot for review!

Kindly be informed that required Units Tests were added.

Also the "accept friendship" is already been available has mentioned in the below screenshot. 

![Screen Shot 2020-11-09 at 10 46 10 AM](https://user-images.githubusercontent.com/44940073/98583487-548f5980-2279-11eb-8a08-f959cb0b06b6.png)

2020-11-09 21:06 UTC, blackpintz requested changes
# Status: Changes Required

### Hello team,

**Great job implementing the requested changes. However, there are still a few fixes needed.**

1). **The user who receives the friendship request should be able to see the accept request button on their profile page and next to their name on the users list page. Instead of a pending request, you should have an accept request button/link.**
users list page | user's page
---------------- | -----------
![userslist](https://user-images.githubusercontent.com/38922385/98590090-53911300-22df-11eb-82ed-8774ced421aa.png) | ![users_page](https://user-images.githubusercontent.com/38922385/98172924-43ee8480-1f03-11eb-9901-11b89d3b6117.png)

2).**The users should not be able to see each other's posts, on their profile pages, until the friendship status is true. Example: Lucy signs in and is able to see Ivy's posts on Ivy's profile yet they are not friends.**

3). **Using another example. After Lucy sends Ivy a request and Ivy accepts the friend request,  there shouldn't be an add friend button for Lucy on Ivy's list page. It should show they are friends instead. Remember you have to make it work without creating another friendship row in the database.**

4). **Using another example. Lucy sends Ivy a friend request and Ivy accepts it. Lucy sees Ivy's posts when Lucy visits her timeline. However, Ivy is not able to see Lucy's posts when Ivy visits her timeline. Please fix that.**

5). **You should include tests for the app/views folder. Check out this [link](https://thoughtbot.com/blog/how-we-test-rails-applications) for more understanding on this.**


## Happy coding 😃.

**PS: You can reach me on slack(Rose Wanjohi).**

2020-11-10 19:47 UTC, bmuhamood commented
- User who receives the friendship request is now able to see the **accept request button** on their profile page and next to their name on the users list page. 
- Removed add friend button when the User Accepts a request. 
- Users can see posts for only accepted friends timeline. 
- Added Views test

2020-11-10 22:31 UTC, kevincappuccino approved these changes
# [STATUS] PROJECT APPROVED 🍾

### I really like your project! Congrats team, you guys did an excellent job, you have my approval to go ahead and merge this pull request!

_**Clean and modular code, following the best practices and the design looks great, keep it up!**_ 🥇



## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

2020-11-10 23:01 UTC, merged