now when the friendship is confirmed == true, there are two row on th…
balerum03/ror-social-scaffold pull request #6
Opened 2020-11-12 16:58 UTC by balerum03

The application now creates two row when the Friendship is confirmed (confirmed == true), this is done with the intention to have a mutual friendship register in the database.

2020-11-12 18:51 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've made laudable progress in this milestone. Most features required seems to be working.__

__You've been informed that during the code review, you will get hints about implementing mutual friendships in the most efficient way, I'm here to do justice to that. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [x] When friendship is confirmed, you can create an additional row by adding this code snippet into your friendship model, like this:

```ruby
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```

- [x] Thanks to the snippet above, we can find user friends only by `user_id` in the friendships table:

```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```

- [x] Also, User#pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```

- [x] At the same time, User#friend_requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```

- [x] In order to get all posts written by a user and their friends, you can create and use a simple method in the User model (in order to NOT do it with Enumerables)

```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends + self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```

- [ ] You did not have any integration tests in your project. Kindly add

**COMMENTS**
Please note that the explanations above concerning implementing mutual friendship are to enable you to see an efficient implementation of mutual friendship. 

In my opinion, it does not mean that you should completely refactor yours to use the method stated above. However, you are advised to see how you can use it to improve your own version of the implementation.


* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2020-11-12 18:51 UTC, teekaytech commented on app/views/users/show.html.erb
> +    <% end %>
Kindly move logic away from views. View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb) 
Check [this](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers) guide to get started with helpers.

2020-11-12 22:38 UTC, bmuhamood commented
- All changes requested by TSE are added to project. 
- Fixed all linters errors.
- All tests added previously are simultaneously working with this project version.

2020-11-12 23:12 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [ ] update the timeline_posts method from your posts_controller to use a method from the User model

```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends + self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```

_this is better than the current one as it uses less number of operations to achieve the same goal_ 

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-11-13 00:44 UTC, balerum03 commented
The suggested code in the last review was pretty much already implemented. We tried to make changes to it but had no success.
The code was already working fine so we returned the code to the last working stage.

2020-11-13 01:37 UTC, Dandush03 approved these changes
# Status: Project Approved :rocket: 
## Great work so far, keep up the good job
# Happy Coding :nerd_face: :comet:

2020-11-13 04:26 UTC, merged